USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE DATABASE PROJETO_LGPD;
USE DATABASE PROJETO_LGPD;

CREATE OR REPLACE TABLE CLIENTES_SENSIVEIS (
    ID_CLIENTE INT,
    NOME VARCHAR(100),
    CPF VARCHAR(14),
    EMAIL VARCHAR(100),
    SALARIO NUMBER(10,2)
);

INSERT INTO CLIENTES_SENSIVEIS VALUES
    (1, 'Lívia Costa', '123.456.789-00', 'livia@email.com', 8500.00),
    (2, 'Carlos Eduardo', '987.654.321-11', 'carlos@email.com', 4200.00),
    (3, 'Mariana Silva', '456.789.123-22', 'mariana@email.com', 12000.00);

GRANT USAGE ON DATABASE PROJETO_LGPD TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA PROJETO_LGPD.PUBLIC TO ROLE PUBLIC;
GRANT SELECT ON TABLE CLIENTES_SENSIVEIS TO ROLE PUBLIC;

CREATE OR REPLACE MASKING POLICY MASK_CPF AS (VAL VARCHAR) RETURNS VARCHAR ->
CASE
  WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN VAL
  ELSE '***.***.***-**'
END;

CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (VAL VARCHAR) RETURNS VARCHAR ->
CASE
  WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN VAL
  ELSE REGEXP_REPLACE(VAL, '(^.{2}).*(@.*$)', '\\1***\\2')
END;

CREATE OR REPLACE MASKING POLICY MASK_SALARIO_RUIDO AS (VAL NUMBER) RETURNS NUMBER ->
CASE
  WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN VAL
  ELSE ROUND(VAL * UNIFORM(0.85, 1.15, RANDOM()), 2)
END;

CREATE OR REPLACE ROW ACCESS POLICY RAP_FILTRO_CLIENTES AS (ID_CLIENTE NUMBER) RETURNS BOOLEAN ->
CASE
  WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN TRUE
  WHEN ID_CLIENTE > 1 THEN TRUE
  ELSE FALSE
END;

ALTER TABLE CLIENTES_SENSIVEIS MODIFY COLUMN CPF SET MASKING POLICY MASK_CPF;
ALTER TABLE CLIENTES_SENSIVEIS MODIFY COLUMN EMAIL SET MASKING POLICY MASK_EMAIL;
ALTER TABLE CLIENTES_SENSIVEIS MODIFY COLUMN SALARIO SET MASKING POLICY MASK_SALARIO_RUIDO;
ALTER TABLE CLIENTES_SENSIVEIS ADD ROW ACCESS POLICY RAP_FILTRO_CLIENTES ON (ID_CLIENTE);

USE ROLE ACCOUNTADMIN;
SELECT * FROM CLIENTES_SENSIVEIS;

USE ROLE PUBLIC;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE PROJETO_LGPD;
SELECT * FROM CLIENTES_SENSIVEIS;
